# CONFIG FILE FOR 2_encode.py

target_sr: 16000 # target sample rate for the audio files 16kHz downsample (max audio freq = 8kHz)
n_fft: 512 # number of samples for the STFT window
n_hop: 128 # number of samples of overlap
win: "hann" # DSP window type for the FFT
eps: 1e-8 # avoid log 0